# Generated by Django 2.2 on 2019-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.TextField(max_length=3)),
                ('currency_to', models.TextField(max_length=3)),
                ('currency_rate', models.FloatField()),
                ('currency_date', models.DateField()),
            ],
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['currency_from', 'currency_to', 'currency_date'], name='sunscrapers_currenc_b067a8_idx'),
        ),
    ]
