# Generated by Django 2.2 on 2019-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunscrapersrss', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['currency_date'], name='sunscrapers_currenc_c465e9_idx'),
        ),
    ]
